# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7dc1a293a4b135a0b3b6582e314caa80ba7f546a703d6137a15e96b53217935519d91f14569b570a72fd8cdce82642c576ec4f98c79b9800827108aa73023a9

test:
  secret_key_base: a1112ea6faad0cb95e6e3d565a7dcf3890c4d461f7ecbad2571eae83700a13296c73b546eff5a45ac38992180aec1d7d9ac0b5fcfe64f73fb7fa7bee0a0a2f9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
